# Generated by Django 5.0 on 2023-12-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namegood', models.CharField(max_length=30)),
                ('specification', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
    ]
