# Generated by Django 5.0 on 2024-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/%y/%m/%d/')),
                ('namegood', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('specification', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
    ]
